import { TopicMeta } from './tutorial.models';

export const TOPICS: readonly TopicMeta[] = [
  {
    id: 'components',
    title: 'Components',
    description: 'Building blocks of Angular applications.',
    icon: '🧩',
    route: '/components',
    difficulty: 'beginner',
    exampleCount: 6,
    tags: ['@Component', 'inputs', 'outputs', 'lifecycle', 'standalone'],
  },
  {
    id: 'templates',
    title: 'Templates',
    description: 'Angular template syntax, directives and data binding.',
    icon: '📄',
    route: '/templates',
    difficulty: 'beginner',
    exampleCount: 6,
    tags: ['interpolation', 'ngIf', 'ngFor', 'pipes', 'two-way binding'],
  },
  {
    id: 'signals',
    title: 'Signals',
    description: 'Reactive primitives for Angular state management.',
    icon: '⚡',
    route: '/signals',
    difficulty: 'intermediate',
    exampleCount: 6,
    tags: ['signal()', 'computed()', 'effect()', 'input()', 'reactivity'],
  },
  {
    id: 'services',
    title: 'Services & DI',
    description: 'Dependency injection, providers and shared state.',
    icon: '🔧',
    route: '/services',
    difficulty: 'intermediate',
    exampleCount: 6,
    tags: ['Injectable', 'inject()', 'providers', 'tokens', 'InjectionToken'],
  },
  {
    id: 'routing',
    title: 'Routing',
    description: 'Navigation, route guards, lazy loading and parameters.',
    icon: '🗺️',
    route: '/routing',
    difficulty: 'intermediate',
    exampleCount: 6,
    tags: ['RouterLink', 'ActivatedRoute', 'Guards', 'Lazy Loading', 'resolvers'],
  },
  {
    id: 'forms',
    title: 'Forms',
    description: 'Template-driven and reactive forms with validation.',
    icon: '📝',
    route: '/forms',
    difficulty: 'intermediate',
    exampleCount: 6,
    tags: ['ReactiveFormsModule', 'FormBuilder', 'Validators', 'FormArray', 'Signal Forms'],
  },
  {
    id: 'http',
    title: 'HTTP & API',
    description: 'HTTP client, interceptors and API integration.',
    icon: '🌐',
    route: '/http',
    difficulty: 'advanced',
    exampleCount: 5,
    tags: ['HttpClient', 'interceptors', 'rxjs', 'error handling', 'resource()'],
  },
  {
    id: 'deferrable-views',
    title: 'Deferrable Views',
    description: 'Lazy rendering with @defer for performance.',
    icon: '⏳',
    route: '/deferrable-views',
    difficulty: 'advanced',
    exampleCount: 5,
    tags: ['@defer', '@loading', '@placeholder', '@error', 'triggers'],
  },
] as const;
